# Generated by Django 4.1.7 on 2023-03-22 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0003_alter_projet_description_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prospet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('adresse', models.CharField(max_length=255)),
                ('tel', models.CharField(max_length=255)),
                ('tel2', models.CharField(max_length=255)),
                ('domaine', models.CharField(max_length=255)),
                ('projet_prospet', models.CharField(max_length=255)),
                ('projet_asso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.projet')),
                ('user_asso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
