# Generated by Django 4.1.7 on 2023-04-04 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_prospet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='tel2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
