# Generated by Django 4.1.7 on 2023-04-10 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0006_alter_prospet_tel2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campagne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('duree', models.DateField()),
                ('lieux', models.CharField(blank=True, max_length=255, null=True)),
                ('motif', models.CharField(blank=True, max_length=255, null=True)),
                ('investissement', models.DecimalField(decimal_places=2, max_digits=10)),
                ('domaine', models.CharField(max_length=255)),
                ('user_asso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
