# Generated by Django 4.1.7 on 2023-04-13 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_prospet_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campagne',
            name='lieux',
        ),
        migrations.AddField(
            model_name='campagne',
            name='region',
            field=models.CharField(blank=True, choices=[('Tunis', 'Tunis'), ('Ariana', 'Ariana'), ('Ben Arous', 'Ben Arous'), ('La Manouba', 'La Manouba'), ('Nabeul', 'Nabeul'), ('Zaghouan', 'Zaghouan'), ('Bizerte', 'Bizerte'), ('Béja', 'Béja'), ('Jendouba', 'Jendouba'), ('Le Kef', 'Le Kef'), ('Siliana', 'Siliana'), ('Kairouan', 'Kairouan'), ('Kassérine', 'Kassérine'), ('Sidi Bouzid', 'Sidi Bouzid'), ('Sousse', 'Sousse'), ('Monastir', 'Monastir'), ('Mahdia', 'Mahdia'), ('Sfax', 'Sfax'), ('Gafsa', 'Gafsa'), ('Tozeur', 'Tozeur'), ('Kébili', 'Kébili'), ('Gabès', 'Gabès'), ('Médenine', 'Médenine'), ('Tataouine', 'Tataouine')], max_length=255, null=True),
        ),
    ]
