# Generated by Django 4.1.7 on 2023-05-06 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='campagne',
            name='projet_asso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.projet', default=1),
            preserve_default=False,
        ),
    ]
