# Generated by Django 4.1.7 on 2023-05-19 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_campagne_projet_asso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='domaine',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='projet_client',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='prospet',
            name='domaine',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='prospet',
            name='projet_prospet',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
