# Generated by Django 4.1.7 on 2023-06-01 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_alter_client_domaine_alter_client_projet_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='progression',
            field=models.IntegerField(default=0),
        ),
    ]
