# Generated by Django 4.1.7 on 2023-06-02 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_projet_progression'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='projet_asso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.projet'),
        ),
        migrations.AlterField(
            model_name='client',
            name='tel',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='prospet',
            name='adresse',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='prospet',
            name='projet_asso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.projet'),
        ),
        migrations.AlterField(
            model_name='prospet',
            name='tel',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
