# Generated by Django 4.1.7 on 2023-04-19 15:51

from django.db import migrations, models
import members.models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default=members.models.get_default_profile_image_url, upload_to='profile_images'),
        ),
    ]
